### ISSUE TITLE
Are the STL models directly available from the manufacturer? 

### ISSUE THREAD

**Issue by Robotawi** [tasada038/denso_cobotta_ros2#1]
Hello @tasada038 Takumi

Thank you for your excellent work and for sharing the project with us. I do have a question, though. I visited the manufacturer's website to look for the STL files of separate links to the robot, but I couldn't find them.

![2023-03-13_20-14](https://user-images.githubusercontent.com/9701369/224687829-01dbfdcb-07bc-4a3c-b5c8-34b86c28bad5.png)

Am I looking in the wrong place? Or do I need to convert the files from STEP format? Please clarify this for me.

Thank you once again for your help.

Thank you!

**Comment by tasada038** [comment]
Hi @Robotawi Mohamed
Great question!

STL models cannot be obtained directly.
It's necessary to convert STEP format to STL files with 3D CAD software (ex. Autodesk Fusion360, Inventor).

Please feel free to contact me if you have any questions.

Thank you!

**Comment by Robotawi** [comment]
Thanks for your reply, @tasada038 

I went through the process, from importing STEP assembly into Fusion 360 to exporting the STL for links. 

However, a problem that I was expecting appeared in Rviz because the STL files not only carry the mesh information but also their coordinates. In this case, the coordinates are missing. Look how the problem shows up in Rviz. 

You made a great project, but not easily reproducible. I am glad we share the same interest. I tried to connect with you on LinkedIn but did not manage to find you. Please feel free to send me an invitation. Here is [my profile](https://www.linkedin.com/in/mohraessa). I would like to keep in touch with a professional like you.

Please feel free to share any thoughts to get this issue fixed. 

Thank you!

**Comment by tasada038** [comment]
Thank you for your question @Robotawi 

Please accept our sincere apologies for the delay in reply.
Also, the image has been removed due to copyright issues.

The downloaded STEP assembly is oriented with the Y-axis up.
Could you position the COBOTTA_BASE at the origin in Fusion 360 with the Z-axis up and rename file written by READEME.md?

You can set the individual joints of the robot by navigating to Assembly > Joints in Fusion 360.
Please consult the manual for the extent of motion of each individual joint.
Moreover, the default pose angle in Rviz is as follows:
J1, J2, J3, J4, J5, J6 = (0, 0, 90, 0, 90, 0)

The proprietary rights relating to any components or parts manufactured by Development company and used in this product, including but not limited to copyrights, trademarks, and other intellectual property rights, shall remain vested in  Development company.
Therefore, the STL file cannot be redistributed. I'm sorry.

I hope this will help you.
Thank you!
